# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2656542eac44f71fc456aef4678e778604840d1fea3a873a6d106ff27542742b2c1f0c9cdf49fb56ea84087105d1416412f7ad9b51ad82da73e7460eb8ecafb7

test:
  secret_key_base: 676801c52b7be997333cb7624139a27eeb9f9fd09d1de5d7314c7da1ce95670336c337d745a93e102f0e9ff40eddf0cb897dcfc82146f2d4f70abec6f195a461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
